document.getElementById("siteTitle").textContent = "JavaScript is working";
document.getElementById("siteSubtitle").textContent = "This is a test.";
document.getElementById("aboutText").textContent = "The script loaded successfully.";
document.getElementById("semesterValue").textContent = "TEST";
document.getElementById("coursesValue").textContent = "5";
document.getElementById("assignmentsValue").textContent = "3/12";
document.getElementById("overallProgressValue").textContent = "25%";
document.getElementById("overallProgressText").textContent = "25% complete";
document.getElementById("overallProgressBar").style.width = "25%";
